name: "Build"
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101'
    - uses: actions/checkout@v2
    - run: dotnet build -c Release
    - run: dotnet test -c Release
    - run: dotnet pack -c Release --output ${{ github.workspace }}\nuget
    - uses: actions/upload-artifact@v1
      with:
        name: nuget-packages
        path: ${{ github.workspace }}\nuget
